jenkins:
  systemMessage: "Welcome to the Chocolatine Powered Marvin Jenkins Instance."
  securityRealm:
    allowSignup: false
  users:
    - id: "Hugom"
      password: ${USER_CHOCOLATEEN_PASSWORD}
      fullName: "Hugo"
    - id: "Garancem"
      password: ${USER_VAUGIE_G_PASSWORD}
      fullName: "Garance"
    - id: "Jeremy"
      password: ${USER_I_DONT_KNOW_PASSWORD}
      fullName: "Jeremy"
    - id: "Nassimm"
      password: ${USER_NASSO_PASSWORD}
      fullName: "Nassim"
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer":
            users: "Hugom"
        - "Job/Build":
            users: "Jeremy"
        - "Job/Workspace":
            users: "Jeremy"
        - "Job/Build":
            users: "Garancem"
        - "Job/Workspace":
            users: "Garancem"
        - "Job/Cancel":
            users: "Garancem"
        - "Overall/Read":
            users: "Nassimm"
folders:
  - name: "Tools"
    description: "Folder for miscellaneous tools."
jobs:
  - script: |
      folder('Tools') {
        displayName('clone-repository')
        parameters {
          string(name: 'GIT_REPOSITORY_URL', description: 'Git URL of the repository to clone')
        }
        steps {
          shell('git clone ${params.GIT_REPOSITORY_URL}')
          cleanWs()
        }
        disabled(false)
        properties([])
        triggers([])
      }
  - script: |
      folder('Tools') {
        displayName('SEED')
        parameters {
          string(name: 'GITHUB_NAME', description: 'GitHub repository owner/repo_name')
          string(name: 'DISPLAY_NAME', description: 'Display name for the job')
        }
        steps {
          jobDsl(targets: ['job_dsl.groovy'])
          cleanWs()
        }
        disabled(false)
        properties([])
        triggers([])
      }
